### ISSUE TITLE
加油，持续关注中。。

### ISSUE THREAD

**Issue by mykioer** [smarttang/sosrp#3]

**Comment by smarttang** [comment]
额，我努力。。

**Comment by lianfeng30** [comment]
账号注册之后 登录有问题
不能登录

**Comment by smarttang** [comment]
最近才抽出时间来，我先看看。你按照wiki的方式注册还是无法登陆么？

**Comment by lianfeng30** [comment]
// 插入用户扩展表
		$data_user_info = array(
			'SRP_USER_HASH_ID' => $hash_id,
			'SRP_USER_STATUS' => 1, # 需要通过审核后才能正常登录平台
			'SRP_USER_EMAIL' => $email,
			'SRP_USER_CREATETIME' => $this->common_model->_datetime(),
			'SRP_USER_LASTLOGIN' => 'null',

改成1 就行了 状态问题  。。。

**Comment by smarttang** [comment]
默认的情况下，只有审核确认后，改变状态才可以登陆，不然随便一个人注册，然后就能登陆很危险。。。毕竟安全是一个比较重要的事情。所以这里才会这样设计～

**Comment by lianfeng30** [comment]
是的 前提是有个账号啊。。。
问题是默认没有账号 ~

**Comment by webvul** [comment]
我把状态改成1还是不行
