### ISSUE TITLE
请问rewrite规则怎么写呢?

### ISSUE THREAD

**Issue by cnwpdb** [smarttang/sosrp#7]
请问rewrite规则怎么写呢?

**Comment by cnwpdb** [comment]
if (!-f $request_filename){
rewrite (.*) /index.php;
}
已经处理好了,贴出来方便后来人

**Comment by smarttang** [comment]
按照wiki上配置本来就不会有问题的啊。为啥就是不去看呢？
https://github.com/smarttang/sosrp/wiki/%E5%B9%B3%E5%8F%B0%E9%85%8D%E7%BD%AE(%E7%8E%AF%E5%A2%83%E6%90%AD%E5%BB%BA)

**Comment by smarttang** [comment]
认真看看wiki把，既然我认真写了，你们都不看，那咋整。
